### PR TITLE
Fix condition for closing the announcement (bots should be excluded).

### PR DESCRIPTION
**Pull request by rxu**

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
You cannot do this. What if god changes value of `is_registered`?

Just joking. Everything okay here. I have reviewed it very intensive.

**Comment by VSEphpbb** [comment]
Uh oh, tests fail, need updating.

**Comment by rxu** [comment]
Now I suppose we have to explicitly set the ```'is_registered'``` status in ```get_controller()```?

**Comment by VSEphpbb** [comment]
Well we are testing against gusts and members so it more likely would need to be set in the data sets too.

Or you could instead do this in which case yeah, just explicitly define is_registered to true in get_controller
```($this->user->data['user_id'] != ANONYMOUS && $this->user->data['is_registered'])```

**Comment by rxu** [comment]
As we use user_id  = 0 in tests dataset, it seems to be correct for is_registered to be true when user_id > 2?

**Comment by VSEphpbb** [comment]
When user is greater than 1 (2 is the founder) and also when user_type = 0 or 3 ;)

**Comment by rxu** [comment]
But we don't have ```user_type``` set in tests?

**Comment by VSEphpbb** [comment]
I was just mentioning it...I looked at what actually defines the is_registered var

**Comment by rxu** [comment]
Oh, ok. I think we can rely on ```user_id > 1``` for now then. Or do you think it's worth adding ```user_type``` thing to the tests as well?

**Comment by VSEphpbb** [comment]
No not worth adding user_type. All that's needed is to add true/false for is_registered to the data sets and then set it up just like the way the user_id is set up in get_controller I believe.

**Comment by VSEphpbb** [comment]
The "Invalid member" data set should have true for is_registered, because that is testing a non-existing user_id/member.

**Comment by rxu** [comment]
Tests passed now.

**Pull request merged**
